"""Add status to raffle

Revision ID: 335eb5bdcc37
Revises: db2178797388
Create Date: 2021-12-08 14:32:25.292914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335eb5bdcc37'
down_revision = 'db2178797388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raffle', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raffle', 'status')
    # ### end Alembic commands ###
